# Generated by Django 2.0.7 on 2018-07-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180716_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='default.png', null=True, upload_to='chapters/%Y/%m/%D'),
        ),
    ]
