# Generated by Django 2.0.7 on 2018-07-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_cv_model_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='default.png', null=True, upload_to='chapters/%Y/%m/%D')),
                ('name_surname', models.CharField(max_length=50)),
                ('born_date', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=150)),
                ('post_office_code', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=50)),
                ('experience', models.TextField(blank=True, null=True)),
                ('education', models.TextField()),
                ('more_education', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='cv_model',
        ),
    ]
