# Generated by Django 2.0.7 on 2018-07-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180717_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
    ]
