# Generated by Django 2.0.7 on 2018-07-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180724_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='chapters/%Y/%m/%D'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='chapters/%Y/%m/%D'),
        ),
    ]
