# Generated by Django 2.0.7 on 2018-07-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_gallery_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
