# Generated by Django 2.0.7 on 2018-07-25 19:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20180725_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='chapters/CVFace')),
                ('about', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cv',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='chapters/CVFace'),
        ),
    ]
